@startuml
title SD -  Configurate an AGV

        participant "WarehouseEmployee" as we
		participant ":ConfigureAGVUI" as ui
		participant ":ConfigureAGVController" as ctrl
		participant ":AGV" as agv
		participant ":JpaRepository" as repo

        we->ui:wants to configure an agv
        activate ui
        ui-->we:asks for agv information
        we->ui:inserts agv information(max weight,volume,status,docker,autonomy,id,model,description)


        ui->ctrl:valueOf(max weight,volume,status,docker,autonomy,id,model,description)
        activate ctrl
        ctrl->repo: create()
        activate repo
        deactivate repo

        ctrl->agv:agv=valueOf(max weight,volume,status,docker,autonomy,id,model,description)
        activate agv
        deactivate agv
        ctrl->repo:add(agv)
        activate repo
        deactivate repo

        deactivate ctrl


        ui-->we:informs the success of the operation
        deactivate ui
@enduml